export const NORMAL_ICON_NAMES = [
  'align-bottom',
  'align-center',
  'align-justify',
  'align-left',
  'align-right',
  'align-top',
  'align-vertically',
  'attachment-2',
  'bold',
  'code-view',
  'double-quotes-l',
  'double-quotes-r',
  'font-color',
  'font-size-2',
  'font-size',
  'format-clear',
  'functions',
  'hashtag',
  'heading',
  'indent-decrease',
  'indent-increase',
  'italic',
  'line-height',
  'link-m',
  'link-unlink-m',
  'link-unlink',
  'link',
  'list-check-2',
  'list-check',
  'list-ordered',
  'list-unordered',
  'omega',
  'page-separator',
  'paragraph',
  'separator',
  'single-quotes-l',
  'single-quotes-r',
  'space',
  'strikethrough-2',
  'strikethrough',
  'subscript-2',
  'subscript',
  'superscript-2',
  'superscript',
  'table-2',
  'text-direction-l',
  'text-direction-r',
  'text-spacing',
  'text-wrap',
  'text',
  'underline',
  'zoom-out-line'
] as const

export const OUTLINED_ICON_NAMES = [
  '4k-line',
  'account-box-line',
  'account-circle-line',
  'account-pin-box-line',
  'account-pin-circle-line',
  'add-box-line',
  'add-circle-line',
  'add-line',
  'admin-line',
  'airplay-line',
  'alarm-line',
  'alarm-warning-line',
  'album-line',
  'alert-line',
  'alipay-line',
  'amazon-line',
  'anchor-line',
  'android-line',
  'angularjs-line',
  'anticlockwise-2-line',
  'anticlockwise-line',
  'apple-line',
  'apps-2-line',
  'apps-line',
  'archive-drawer-line',
  'archive-line',
  'arrow-down-circle-line',
  'arrow-down-line',
  'arrow-down-s-line',
  'arrow-drop-down-line',
  'arrow-drop-left-line',
  'arrow-drop-right-line',
  'arrow-drop-up-line',
  'arrow-go-back-line',
  'arrow-go-forward-line',
  'arrow-left-circle-line',
  'arrow-left-down-line',
  'arrow-left-line',
  'arrow-left-s-line',
  'arrow-left-up-line',
  'arrow-right-circle-line',
  'arrow-right-down-line',
  'arrow-right-line',
  'arrow-right-s-line',
  'arrow-right-up-line',
  'arrow-up-circle-line',
  'arrow-up-line',
  'arrow-up-s-line',
  'artboard-2-line',
  'artboard-line',
  'article-line',
  'at-line',
  'attachment-line',
  'award-line',
  'baidu-line',
  'ball-pen-line',
  'bank-card-2-line',
  'bank-card-line',
  'bank-line',
  'bar-chart-2-line',
  'bar-chart-box-line',
  'bar-chart-grouped-line',
  'bar-chart-horizontal-line',
  'bar-chart-line',
  'barcode-box-line',
  'barcode-line',
  'barricade-line',
  'base-station-line',
  'battery-2-charge-line',
  'battery-2-line',
  'battery-charge-line',
  'battery-line',
  'battery-low-line',
  'behance-line',
  'bike-line',
  'bill-line',
  'bit-coin-line',
  'bluetooth-connect-line',
  'bluetooth-line',
  'blur-off-line',
  'book-2-line',
  'book-3-line',
  'book-line',
  'book-mark-line',
  'book-open-line',
  'book-read-line',
  'bookmark-2-line',
  'bookmark-3-line',
  'bookmark-line',
  'braces-line',
  'brackets-line',
  'briefcase-2-line',
  'briefcase-3-line',
  'briefcase-4-line',
  'briefcase-5-line',
  'briefcase-line',
  'broadcast-line',
  'brush-2-line',
  'brush-3-line',
  'brush-4-line',
  'brush-line',
  'bug-2-line',
  'bug-line',
  'building-2-line',
  'building-3-line',
  'building-4-line',
  'building-line',
  'bus-2-line',
  'bus-line',
  'calculator-line',
  'calendar-2-line',
  'calendar-event-line',
  'calendar-line',
  'calendar-todo-line',
  'camera-2-line',
  'camera-3-line',
  'camera-lens-line',
  'camera-line',
  'camera-off-line',
  'camera-switch-line',
  'car-line',
  'car-washing-line',
  'cast-line',
  'cellphone-line',
  'celsius-line',
  'charging-pile-2-line',
  'charging-pile-line',
  'chat-1-line',
  'chat-2-line',
  'chat-3-line',
  'chat-4-line',
  'chat-check-line',
  'chat-delete-line',
  'chat-download-line',
  'chat-forward-line',
  'chat-heart-line',
  'chat-new-line',
  'chat-settings-line',
  'chat-smile-2-line',
  'chat-smile-3-line',
  'chat-smile-line',
  'chat-upload-line',
  'chat-voice-line',
  'check-double-line',
  'check-line',
  'checkbox-blank-circle-line',
  'checkbox-blank-line',
  'checkbox-circle-line',
  'checkbox-indeterminate-line',
  'checkbox-line',
  'checkbox-multiple-blank-line',
  'checkbox-multiple-line',
  'china-railway-line',
  'chrome-line',
  'clapperboard-line',
  'clipboard-line',
  'clockwise-2-line',
  'clockwise-line',
  'close-circle-line',
  'close-line',
  'cloud-line',
  'cloud-windy-line',
  'cloudy-2-line',
  'cloudy-line',
  'code-box-line',
  'code-line',
  'code-s-line',
  'code-s-slash-line',
  'codepen-line',
  'command-line',
  'community-line',
  'compass-2-line',
  'compass-3-line',
  'compass-4-line',
  'compass-discover-line',
  'compass-line',
  'compasses-2-line',
  'compasses-line',
  'computer-line',
  'contacts-book-2-line',
  'contacts-book-line',
  'contacts-line',
  'contrast-2-line',
  'contrast-drop-2-line',
  'contrast-drop-line',
  'contrast-line',
  'copper-coin-line',
  'copper-diamond-line',
  'coreos-line',
  'coupon-2-line',
  'coupon-3-line',
  'coupon-4-line',
  'coupon-5-line',
  'coupon-line',
  'cpu-line',
  'crop-2-line',
  'crop-line',
  'css3-line',
  'cup-line',
  'currency-line',
  'cursor-line',
  'customer-service-2-line',
  'customer-service-line',
  'dashboard-line',
  'database-2-line',
  'database-line',
  'delete-back-2-line',
  'delete-back-line',
  'delete-bin-2-line',
  'delete-bin-3-line',
  'delete-bin-4-line',
  'delete-bin-5-line',
  'delete-bin-6-line',
  'delete-bin-7-line',
  'delete-bin-line',
  'device-line',
  'dingding-line',
  'direction-line',
  'disc-line',
  'discord-line',
  'discuss-line',
  'divide-line',
  'door-lock-box-line',
  'door-lock-line',
  'douban-line',
  'download-2-line',
  'download-cloud-line',
  'download-line',
  'drag-move-2-line',
  'drag-move-line',
  'dribbble-line',
  'drive-line',
  'drizzle-line',
  'drop-line',
  'dropbox-line',
  'dv-line',
  'dvd-line',
  'e-bike-2-line',
  'e-bike-line',
  'earth-line',
  'edge-line',
  'edit-2-line',
  'edit-box-line',
  'edit-circle-line',
  'edit-line',
  'eject-line',
  'emotion-2-line',
  'emotion-happy-line',
  'emotion-line',
  'emotion-normal-line',
  'emotion-unhappy-line',
  'equalizer-line',
  'eraser-line',
  'error-warning-line',
  'evernote-line',
  'exchange-box-line',
  'exchange-cny-line',
  'exchange-dollar-line',
  'exchange-funds-line',
  'exchange-line',
  'eye-close-line',
  'eye-line',
  'eye-off-line',
  'facebook-box-line',
  'facebook-circle-line',
  'facebook-line',
  'fahrenheit-line',
  'feedback-line',
  'file-2-line',
  'file-3-line',
  'file-4-line',
  'file-add-line',
  'file-chart-2-line',
  'file-chart-line',
  'file-code-line',
  'file-copy-2-line',
  'file-copy-line',
  'file-damage-line',
  'file-download-line',
  'file-edit-line',
  'file-excel-2-line',
  'file-excel-line',
  'file-forbid-line',
  'file-info-line',
  'file-line',
  'file-list-2-line',
  'file-list-3-line',
  'file-list-line',
  'file-lock-line',
  'file-mark-line',
  'file-music-line',
  'file-paper-line',
  'file-pdf-line',
  'file-ppt-2-line',
  'file-ppt-line',
  'file-reduce-line',
  'file-search-line',
  'file-settings-line',
  'file-shield-2-line',
  'file-shield-line',
  'file-shred-line',
  'file-text-line',
  'file-transfer-line',
  'file-unknow-line',
  'file-upload-line',
  'file-user-line',
  'file-warning-line',
  'file-word-2-line',
  'file-word-line',
  'file-zip-line',
  'film-line',
  'filter-2-line',
  'filter-3-line',
  'filter-line',
  'find-replace-line',
  'fire-line',
  'firefox-line',
  'flag-2-line',
  'flag-line',
  'flash-circle-line',
  'flashlight-line',
  'flight-land-line',
  'flight-takeoff-line',
  'focus-2-line',
  'focus-line',
  'foggy-line',
  'folder-2-line',
  'folder-3-line',
  'folder-4-line',
  'folder-5-line',
  'folder-add-line',
  'folder-chart-2-line',
  'folder-chart-line',
  'folder-download-line',
  'folder-forbid-line',
  'folder-info-line',
  'folder-line',
  'folder-lock-line',
  'folder-music-line',
  'folder-received-line',
  'folder-reduce-line',
  'folder-settings-line',
  'folder-shared-line',
  'folder-shield-2-line',
  'folder-shield-line',
  'folder-transfer-line',
  'folder-unknow-line',
  'folder-upload-line',
  'folder-user-line',
  'folder-warning-line',
  'folders-line',
  'footprint-line',
  'forbid-2-line',
  'forbid-line',
  'fullscreen-exit-line',
  'fullscreen-line',
  'function-line',
  'funds-box-line',
  'funds-line',
  'gallery-line',
  'gas-station-line',
  'genderless-line',
  'git-branch-line',
  'git-commit-line',
  'git-merge-line',
  'git-pull-request-line',
  'git-repository-commits-line',
  'git-repository-line',
  'git-repository-private-line',
  'github-line',
  'gitlab-line',
  'global-line',
  'globe-line',
  'goblet-line',
  'google-line',
  'government-line',
  'gps-line',
  'gradienter-line',
  'grid-line',
  'group-2-line',
  'group-line',
  'guide-line',
  'hail-line',
  'hard-drive-2-line',
  'hard-drive-line',
  'haze-line',
  'hd-line',
  'headphone-line',
  'heart-2-line',
  'heart-line',
  'heavy-showers-line',
  'home-2-line',
  'home-3-line',
  'home-4-line',
  'home-5-line',
  'home-6-line',
  'home-7-line',
  'home-8-line',
  'home-gear-line',
  'home-heart-line',
  'home-line',
  'home-smile-2-line',
  'home-smile-line',
  'home-wifi-line',
  'honour-line',
  'hospital-line',
  'hotel-bed-line',
  'hotel-line',
  'hq-line',
  'html5-line',
  'ie-line',
  'image-2-line',
  'image-line',
  'inbox-archive-line',
  'inbox-line',
  'increase-decrease-line',
  'indeterminate-circle-line',
  'information-line',
  'input-method-line',
  'instagram-line',
  'invision-line',
  'kakao-talk-line',
  'key-2-line',
  'key-line',
  'keyboard-box-line',
  'keyboard-line',
  'keynote-line',
  'landscape-line',
  'layout-column-line',
  'layout-line',
  'layout-row-line',
  'lightbulb-flash-line',
  'lightbulb-line',
  'line-line',
  'linkedin-box-line',
  'linkedin-line',
  'links-line',
  'list-settings-line',
  'loader-2-line',
  'loader-3-line',
  'loader-4-line',
  'loader-5-line',
  'loader-line',
  'lock-2-line',
  'lock-line',
  'lock-password-line',
  'lock-unlock-line',
  'login-box-line',
  'login-circle-line',
  'logout-box-line',
  'logout-circle-line',
  'mac-line',
  'macbook-line',
  'magic-line',
  'mail-add-line',
  'mail-check-line',
  'mail-close-line',
  'mail-download-line',
  'mail-forbid-line',
  'mail-line',
  'mail-lock-line',
  'mail-open-line',
  'mail-send-line',
  'mail-settings-line',
  'mail-star-line',
  'mail-unread-line',
  'map-2-line',
  'map-line',
  'map-pin-2-line',
  'map-pin-3-line',
  'map-pin-4-line',
  'map-pin-5-line',
  'map-pin-add-line',
  'map-pin-line',
  'map-pin-range-line',
  'map-pin-time-line',
  'map-pin-user-line',
  'mark-pen-line',
  'markdown-line',
  'markup-line',
  'mastercard-line',
  'mastodon-line',
  'medium-line',
  'men-line',
  'menu-2-line',
  'menu-3-line',
  'menu-line',
  'message-2-line',
  'message-3-line',
  'message-line',
  'messenger-line',
  'mic-2-line',
  'mic-line',
  'mic-off-line',
  'mini-program-line',
  'mist-line',
  'money-cny-box-line',
  'money-cny-circle-line',
  'money-dollar-box-line',
  'money-dollar-circle-line',
  'money-euro-box-line',
  'money-euro-circle-line',
  'money-pound-box-line',
  'money-pound-circle-line',
  'moon-clear-line',
  'moon-cloudy-line',
  'moon-foggy-line',
  'moon-line',
  'more-2-line',
  'more-line',
  'motorbike-line',
  'mouse-line',
  'movie-2-line',
  'movie-line',
  'music-2-line',
  'music-line',
  'mv-line',
  'navigation-line',
  'netease-cloud-music-line',
  'netflix-line',
  'newspaper-line',
  'notification-2-line',
  'notification-3-line',
  'notification-4-line',
  'notification-badge-line',
  'notification-line',
  'notification-off-line',
  'numbers-line',
  'oil-line',
  'open-arm-line',
  'opera-line',
  'order-play-line',
  'outlet-2-line',
  'outlet-line',
  'pages-line',
  'paint-brush-line',
  'paint-line',
  'palette-line',
  'pantone-line',
  'parent-line',
  'parentheses-line',
  'parking-box-line',
  'parking-line',
  'patreon-line',
  'pause-circle-line',
  'pause-line',
  'pause-mini-line',
  'paypal-line',
  'pen-nib-line',
  'pencil-line',
  'pencil-ruler-2-line',
  'pencil-ruler-line',
  'percent-line',
  'phone-camera-line',
  'phone-line',
  'pie-chart-2-line',
  'pie-chart-box-line',
  'pie-chart-line',
  'pin-distance-line',
  'pinterest-line',
  'plane-line',
  'play-circle-line',
  'play-line',
  'play-list-add-line',
  'play-list-line',
  'play-mini-line',
  'playstation-line',
  'plug-2-line',
  'plug-line',
  'polaroid-2-line',
  'polaroid-line',
  'police-car-line',
  'price-tag-2-line',
  'price-tag-3-line',
  'price-tag-line',
  'printer-line',
  'product-hunt-line',
  'profile-line',
  'projector-2-line',
  'projector-line',
  'qq-line',
  'qr-code-line',
  'qr-scan-2-line',
  'qr-scan-line',
  'question-answer-line',
  'question-line',
  'questionnaire-line',
  'quill-pen-line',
  'radar-line',
  'radio-2-line',
  'radio-button-line',
  'radio-line',
  'rainy-line',
  'reactjs-line',
  'record-circle-line',
  'record-mail-line',
  'red-packet-line',
  'reddit-line',
  'refresh-line',
  'refund-line',
  'remixicon-line',
  'repeat-2-line',
  'repeat-line',
  'repeat-one-line',
  'reply-line',
  'reserved-line',
  'restart-line',
  'restaurant-2-line',
  'restaurant-line',
  'rewind-line',
  'rewind-mini-line',
  'rhythm-line',
  'riding-line',
  'road-map-line',
  'roadster-line',
  'robot-line',
  'rocket-2-line',
  'rocket-line',
  'route-line',
  'router-line',
  'rss-line',
  'ruler-2-line',
  'ruler-line',
  'run-line',
  'safari-line',
  'safe-2-line',
  'safe-line',
  'sailboat-line',
  'save-2-line',
  'save-3-line',
  'save-line',
  'scan-2-line',
  'scan-line',
  'scissors-2-line',
  'scissors-cut-line',
  'scissors-line',
  'screenshot-2-line',
  'screenshot-line',
  'sd-card-line',
  'sd-card-mini-line',
  'search-2-line',
  'search-eye-line',
  'search-line',
  'send-plane-2-line',
  'send-plane-line',
  'sensor-line',
  'server-line',
  'settings-2-line',
  'settings-3-line',
  'settings-4-line',
  'settings-5-line',
  'settings-6-line',
  'settings-line',
  'shape-2-line',
  'shape-line',
  'share-box-line',
  'share-circle-line',
  'share-forward-2-line',
  'share-forward-box-line',
  'share-forward-line',
  'share-line',
  'shield-cross-line',
  'shield-flash-line',
  'shield-line',
  'shield-star-line',
  'shield-user-line',
  'ship-2-line',
  'ship-line',
  'shirt-line',
  'shopping-bag-2-line',
  'shopping-bag-3-line',
  'shopping-bag-line',
  'shopping-cart-2-line',
  'shopping-cart-line',
  'showers-line',
  'shuffle-line',
  'shut-down-line',
  'side-bar-line',
  'signal-tower-line',
  'sim-card-2-line',
  'sim-card-line',
  'sip-line',
  'skip-back-line',
  'skip-back-mini-line',
  'skip-forward-line',
  'skip-forward-mini-line',
  'skull-line',
  'skype-line',
  'slack-line',
  'slice-line',
  'slideshow-2-line',
  'slideshow-3-line',
  'slideshow-4-line',
  'slideshow-line',
  'smartphone-line',
  'snapchat-line',
  'snowy-line',
  'sound-module-line',
  'space-ship-line',
  'spam-2-line',
  'spam-3-line',
  'spam-line',
  'speaker-2-line',
  'speaker-3-line',
  'speaker-line',
  'speed-line',
  'speed-mini-line',
  'spotify-line',
  'stack-line',
  'stack-overflow-line',
  'star-half-line',
  'star-half-s-line',
  'star-line',
  'star-s-line',
  'stock-line',
  'stop-circle-line',
  'stop-line',
  'stop-mini-line',
  'store-2-line',
  'store-3-line',
  'store-line',
  'subtract-line',
  'subway-line',
  'sun-cloudy-line',
  'sun-foggy-line',
  'sun-line',
  'surround-sound-line',
  'swap-box-line',
  'swap-line',
  'switch-line',
  't-box-line',
  't-shirt-line',
  'table-line',
  'tablet-line',
  'taobao-line',
  'tape-line',
  'task-line',
  'taxi-line',
  'telegram-line',
  'temp-cold-line',
  'temp-hot-line',
  'terminal-box-line',
  'terminal-line',
  'terminal-window-line',
  'thumb-down-line',
  'thumb-up-line',
  'thunderstorms-line',
  'time-line',
  'timer-2-line',
  'timer-flash-line',
  'timer-line',
  'todo-line',
  'toggle-line',
  'tornado-line',
  'traffic-light-line',
  'train-line',
  'travesti-line',
  'treasure-map-line',
  'trello-line',
  'trophy-line',
  'truck-line',
  'tumblr-line',
  'tv-2-line',
  'tv-line',
  'twitter-line',
  'u-disk-line',
  'ubuntu-line',
  'umbrella-line',
  'upload-2-line',
  'upload-cloud-line',
  'upload-line',
  'user-2-line',
  'user-3-line',
  'user-4-line',
  'user-5-line',
  'user-add-line',
  'user-follow-line',
  'user-line',
  'user-location-line',
  'user-received-2-line',
  'user-received-line',
  'user-search-line',
  'user-settings-line',
  'user-shared-2-line',
  'user-shared-line',
  'user-smile-line',
  'user-star-line',
  'user-unfollow-line',
  'user-voice-line',
  'video-chat-line',
  'video-line',
  'vidicon-2-line',
  'vidicon-line',
  'vip-crown-2-line',
  'vip-crown-line',
  'vip-diamond-line',
  'vip-line',
  'visa-line',
  'voiceprint-line',
  'volume-down-line',
  'volume-mute-line',
  'volume-up-line',
  'vuejs-line',
  'walk-line',
  'wallet-2-line',
  'wallet-3-line',
  'wallet-line',
  'water-flash-line',
  'webcam-line',
  'wechat-2-line',
  'wechat-line',
  'wechat-pay-line',
  'weibo-line',
  'whatsapp-line',
  'wifi-line',
  'window-2-line',
  'window-line',
  'windows-line',
  'windy-line',
  'women-line',
  'xbox-line',
  'youtube-line',
  'zcool-line',
  'zhihu-line',
  'zoom-in-line',
  'zoom-out-line'
] as const

export const FILLED_ICON_NAMES = [
  '4k-fill',
  'account-box-fill',
  'account-circle-fill',
  'account-pin-box-fill',
  'account-pin-circle-fill',
  'add-box-fill',
  'add-circle-fill',
  'add-fill',
  'admin-fill',
  'airplay-fill',
  'alarm-fill',
  'alarm-warning-fill',
  'album-fill',
  'alert-fill',
  'alipay-fill',
  'amazon-fill',
  'anchor-fill',
  'android-fill',
  'angularjs-fill',
  'anticlockwise-2-fill',
  'anticlockwise-fill',
  'apple-fill',
  'apps-2-fill',
  'apps-fill',
  'archive-drawer-fill',
  'archive-fill',
  'arrow-down-circle-fill',
  'arrow-down-fill',
  'arrow-down-s-fill',
  'arrow-drop-down-fill',
  'arrow-drop-left-fill',
  'arrow-drop-right-fill',
  'arrow-drop-up-fill',
  'arrow-go-back-fill',
  'arrow-go-forward-fill',
  'arrow-left-circle-fill',
  'arrow-left-down-fill',
  'arrow-left-fill',
  'arrow-left-s-fill',
  'arrow-left-up-fill',
  'arrow-right-circle-fill',
  'arrow-right-down-fill',
  'arrow-right-fill',
  'arrow-right-s-fill',
  'arrow-right-up-fill',
  'arrow-up-circle-fill',
  'arrow-up-fill',
  'arrow-up-s-fill',
  'artboard-2-fill',
  'artboard-fill',
  'article-fill',
  'at-fill',
  'attachment-fill',
  'award-fill',
  'baidu-fill',
  'ball-pen-fill',
  'bank-card-2-fill',
  'bank-card-fill',
  'bank-fill',
  'bar-chart-2-fill',
  'bar-chart-box-fill',
  'bar-chart-fill',
  'bar-chart-grouped-fill',
  'bar-chart-horizontal-fill',
  'barcode-box-fill',
  'barcode-fill',
  'barricade-fill',
  'base-station-fill',
  'battery-2-charge-fill',
  'battery-2-fill',
  'battery-charge-fill',
  'battery-fill',
  'battery-low-fill',
  'behance-fill',
  'bike-fill',
  'bill-fill',
  'bit-coin-fill',
  'bluetooth-connect-fill',
  'bluetooth-fill',
  'blur-off-fill',
  'book-2-fill',
  'book-3-fill',
  'book-fill',
  'book-mark-fill',
  'book-open-fill',
  'book-read-fill',
  'bookmark-2-fill',
  'bookmark-3-fill',
  'bookmark-fill',
  'braces-fill',
  'brackets-fill',
  'briefcase-2-fill',
  'briefcase-3-fill',
  'briefcase-4-fill',
  'briefcase-5-fill',
  'briefcase-fill',
  'broadcast-fill',
  'brush-2-fill',
  'brush-3-fill',
  'brush-4-fill',
  'brush-fill',
  'bug-2-fill',
  'bug-fill',
  'building-2-fill',
  'building-3-fill',
  'building-4-fill',
  'building-fill',
  'bus-2-fill',
  'bus-fill',
  'calculator-fill',
  'calendar-2-fill',
  'calendar-event-fill',
  'calendar-fill',
  'calendar-todo-fill',
  'camera-2-fill',
  'camera-3-fill',
  'camera-fill',
  'camera-lens-fill',
  'camera-off-fill',
  'camera-switch-fill',
  'car-fill',
  'car-washing-fill',
  'cast-fill',
  'cellphone-fill',
  'celsius-fill',
  'charging-pile-2-fill',
  'charging-pile-fill',
  'chat-1-fill',
  'chat-2-fill',
  'chat-3-fill',
  'chat-4-fill',
  'chat-check-fill',
  'chat-delete-fill',
  'chat-download-fill',
  'chat-forward-fill',
  'chat-heart-fill',
  'chat-new-fill',
  'chat-settings-fill',
  'chat-smile-2-fill',
  'chat-smile-3-fill',
  'chat-smile-fill',
  'chat-upload-fill',
  'chat-voice-fill',
  'check-double-fill',
  'check-fill',
  'checkbox-blank-circle-fill',
  'checkbox-blank-fill',
  'checkbox-circle-fill',
  'checkbox-fill',
  'checkbox-indeterminate-fill',
  'checkbox-multiple-blank-fill',
  'checkbox-multiple-fill',
  'china-railway-fill',
  'chrome-fill',
  'clapperboard-fill',
  'clipboard-fill',
  'clockwise-2-fill',
  'clockwise-fill',
  'close-circle-fill',
  'close-fill',
  'cloud-fill',
  'cloud-windy-fill',
  'cloudy-2-fill',
  'cloudy-fill',
  'code-box-fill',
  'code-fill',
  'code-s-fill',
  'code-s-slash-fill',
  'codepen-fill',
  'command-fill',
  'community-fill',
  'compass-2-fill',
  'compass-3-fill',
  'compass-4-fill',
  'compass-discover-fill',
  'compass-fill',
  'compasses-2-fill',
  'compasses-fill',
  'computer-fill',
  'contacts-book-2-fill',
  'contacts-book-fill',
  'contacts-fill',
  'contrast-2-fill',
  'contrast-drop-2-fill',
  'contrast-drop-fill',
  'contrast-fill',
  'copper-coin-fill',
  'copper-diamond-fill',
  'coreos-fill',
  'coupon-2-fill',
  'coupon-3-fill',
  'coupon-4-fill',
  'coupon-5-fill',
  'coupon-fill',
  'cpu-fill',
  'crop-2-fill',
  'crop-fill',
  'css3-fill',
  'cup-fill',
  'currency-fill',
  'cursor-fill',
  'customer-service-2-fill',
  'customer-service-fill',
  'dashboard-fill',
  'database-2-fill',
  'database-fill',
  'delete-back-2-fill',
  'delete-back-fill',
  'delete-bin-2-fill',
  'delete-bin-3-fill',
  'delete-bin-4-fill',
  'delete-bin-5-fill',
  'delete-bin-6-fill',
  'delete-bin-7-fill',
  'delete-bin-fill',
  'device-fill',
  'dingding-fill',
  'direction-fill',
  'disc-fill',
  'discord-fill',
  'discuss-fill',
  'divide-fill',
  'door-lock-box-fill',
  'door-lock-fill',
  'douban-fill',
  'download-2-fill',
  'download-cloud-fill',
  'download-fill',
  'drag-move-2-fill',
  'drag-move-fill',
  'dribbble-fill',
  'drive-fill',
  'drizzle-fill',
  'drop-fill',
  'dropbox-fill',
  'dv-fill',
  'dvd-fill',
  'e-bike-2-fill',
  'e-bike-fill',
  'earth-fill',
  'edge-fill',
  'edit-2-fill',
  'edit-box-fill',
  'edit-circle-fill',
  'edit-fill',
  'eject-fill',
  'emotion-2-fill',
  'emotion-fill',
  'emotion-happy-fill',
  'emotion-normal-fill',
  'emotion-unhappy-fill',
  'equalizer-fill',
  'eraser-fill',
  'error-warning-fill',
  'evernote-fill',
  'exchange-box-fill',
  'exchange-cny-fill',
  'exchange-dollar-fill',
  'exchange-fill',
  'exchange-funds-fill',
  'eye-close-fill',
  'eye-fill',
  'eye-off-fill',
  'facebook-box-fill',
  'facebook-circle-fill',
  'facebook-fill',
  'fahrenheit-fill',
  'feedback-fill',
  'file-2-fill',
  'file-3-fill',
  'file-4-fill',
  'file-add-fill',
  'file-chart-2-fill',
  'file-chart-fill',
  'file-code-fill',
  'file-copy-2-fill',
  'file-copy-fill',
  'file-damage-fill',
  'file-download-fill',
  'file-edit-fill',
  'file-excel-2-fill',
  'file-excel-fill',
  'file-fill',
  'file-forbid-fill',
  'file-info-fill',
  'file-list-2-fill',
  'file-list-3-fill',
  'file-list-fill',
  'file-lock-fill',
  'file-mark-fill',
  'file-music-fill',
  'file-paper-fill',
  'file-pdf-fill',
  'file-ppt-2-fill',
  'file-ppt-fill',
  'file-reduce-fill',
  'file-search-fill',
  'file-settings-fill',
  'file-shield-2-fill',
  'file-shield-fill',
  'file-shred-fill',
  'file-text-fill',
  'file-transfer-fill',
  'file-unknow-fill',
  'file-upload-fill',
  'file-user-fill',
  'file-warning-fill',
  'file-word-2-fill',
  'file-word-fill',
  'file-zip-fill',
  'film-fill',
  'filter-2-fill',
  'filter-3-fill',
  'filter-fill',
  'find-replace-fill',
  'fire-fill',
  'firefox-fill',
  'flag-2-fill',
  'flag-fill',
  'flash-circle-fill',
  'flashlight-fill',
  'flight-land-fill',
  'flight-takeoff-fill',
  'focus-2-fill',
  'focus-fill',
  'foggy-fill',
  'folder-2-fill',
  'folder-3-fill',
  'folder-4-fill',
  'folder-5-fill',
  'folder-add-fill',
  'folder-chart-2-fill',
  'folder-chart-fill',
  'folder-download-fill',
  'folder-fill',
  'folder-forbid-fill',
  'folder-info-fill',
  'folder-lock-fill',
  'folder-music-fill',
  'folder-received-fill',
  'folder-reduce-fill',
  'folder-settings-fill',
  'folder-shared-fill',
  'folder-shield-2-fill',
  'folder-shield-fill',
  'folder-transfer-fill',
  'folder-unknow-fill',
  'folder-upload-fill',
  'folder-user-fill',
  'folder-warning-fill',
  'folders-fill',
  'footprint-fill',
  'forbid-2-fill',
  'forbid-fill',
  'fullscreen-exit-fill',
  'fullscreen-fill',
  'function-fill',
  'funds-box-fill',
  'funds-fill',
  'gallery-fill',
  'gas-station-fill',
  'genderless-fill',
  'git-branch-fill',
  'git-commit-fill',
  'git-merge-fill',
  'git-pull-request-fill',
  'git-repository-commits-fill',
  'git-repository-fill',
  'git-repository-private-fill',
  'github-fill',
  'gitlab-fill',
  'global-fill',
  'globe-fill',
  'goblet-fill',
  'google-fill',
  'government-fill',
  'gps-fill',
  'gradienter-fill',
  'grid-fill',
  'group-2-fill',
  'group-fill',
  'guide-fill',
  'hail-fill',
  'hard-drive-2-fill',
  'hard-drive-fill',
  'haze-fill',
  'hd-fill',
  'headphone-fill',
  'heart-2-fill',
  'heart-fill',
  'heavy-showers-fill',
  'home-2-fill',
  'home-3-fill',
  'home-4-fill',
  'home-5-fill',
  'home-6-fill',
  'home-7-fill',
  'home-8-fill',
  'home-fill',
  'home-gear-fill',
  'home-heart-fill',
  'home-smile-2-fill',
  'home-smile-fill',
  'home-wifi-fill',
  'honour-fill',
  'hospital-fill',
  'hotel-bed-fill',
  'hotel-fill',
  'hq-fill',
  'html5-fill',
  'ie-fill',
  'image-2-fill',
  'image-fill',
  'inbox-archive-fill',
  'inbox-fill',
  'increase-decrease-fill',
  'indeterminate-circle-fill',
  'information-fill',
  'input-method-fill',
  'instagram-fill',
  'invision-fill',
  'kakao-talk-fill',
  'key-2-fill',
  'key-fill',
  'keyboard-box-fill',
  'keyboard-fill',
  'keynote-fill',
  'landscape-fill',
  'layout-column-fill',
  'layout-fill',
  'layout-row-fill',
  'lightbulb-fill',
  'lightbulb-flash-fill',
  'line-fill',
  'linkedin-box-fill',
  'linkedin-fill',
  'links-fill',
  'list-settings-fill',
  'loader-2-fill',
  'loader-3-fill',
  'loader-4-fill',
  'loader-5-fill',
  'loader-fill',
  'lock-2-fill',
  'lock-fill',
  'lock-password-fill',
  'lock-unlock-fill',
  'login-box-fill',
  'login-circle-fill',
  'logout-box-fill',
  'logout-circle-fill',
  'mac-fill',
  'macbook-fill',
  'magic-fill',
  'mail-add-fill',
  'mail-check-fill',
  'mail-close-fill',
  'mail-download-fill',
  'mail-fill',
  'mail-forbid-fill',
  'mail-lock-fill',
  'mail-open-fill',
  'mail-send-fill',
  'mail-settings-fill',
  'mail-star-fill',
  'mail-unread-fill',
  'map-2-fill',
  'map-fill',
  'map-pin-2-fill',
  'map-pin-3-fill',
  'map-pin-4-fill',
  'map-pin-5-fill',
  'map-pin-add-fill',
  'map-pin-fill',
  'map-pin-range-fill',
  'map-pin-time-fill',
  'map-pin-user-fill',
  'mark-pen-fill',
  'markdown-fill',
  'markup-fill',
  'mastercard-fill',
  'mastodon-fill',
  'medium-fill',
  'men-fill',
  'menu-2-fill',
  'menu-3-fill',
  'menu-fill',
  'message-2-fill',
  'message-3-fill',
  'message-fill',
  'messenger-fill',
  'mic-2-fill',
  'mic-fill',
  'mic-off-fill',
  'mini-program-fill',
  'mist-fill',
  'money-cny-box-fill',
  'money-cny-circle-fill',
  'money-dollar-box-fill',
  'money-dollar-circle-fill',
  'money-euro-box-fill',
  'money-euro-circle-fill',
  'money-pound-box-fill',
  'money-pound-circle-fill',
  'moon-clear-fill',
  'moon-cloudy-fill',
  'moon-fill',
  'moon-foggy-fill',
  'more-2-fill',
  'more-fill',
  'motorbike-fill',
  'mouse-fill',
  'movie-2-fill',
  'movie-fill',
  'music-2-fill',
  'music-fill',
  'mv-fill',
  'navigation-fill',
  'netease-cloud-music-fill',
  'netflix-fill',
  'newspaper-fill',
  'notification-2-fill',
  'notification-3-fill',
  'notification-4-fill',
  'notification-badge-fill',
  'notification-fill',
  'notification-off-fill',
  'numbers-fill',
  'oil-fill',
  'open-arm-fill',
  'opera-fill',
  'order-play-fill',
  'outlet-2-fill',
  'outlet-fill',
  'pages-fill',
  'paint-brush-fill',
  'paint-fill',
  'palette-fill',
  'pantone-fill',
  'parent-fill',
  'parentheses-fill',
  'parking-box-fill',
  'parking-fill',
  'patreon-fill',
  'pause-circle-fill',
  'pause-fill',
  'pause-mini-fill',
  'paypal-fill',
  'pen-nib-fill',
  'pencil-fill',
  'pencil-ruler-2-fill',
  'pencil-ruler-fill',
  'percent-fill',
  'phone-camera-fill',
  'phone-fill',
  'pie-chart-2-fill',
  'pie-chart-box-fill',
  'pie-chart-fill',
  'pin-distance-fill',
  'pinterest-fill',
  'plane-fill',
  'play-circle-fill',
  'play-fill',
  'play-list-add-fill',
  'play-list-fill',
  'play-mini-fill',
  'playstation-fill',
  'plug-2-fill',
  'plug-fill',
  'polaroid-2-fill',
  'polaroid-fill',
  'police-car-fill',
  'price-tag-2-fill',
  'price-tag-3-fill',
  'price-tag-fill',
  'printer-fill',
  'product-hunt-fill',
  'profile-fill',
  'projector-2-fill',
  'projector-fill',
  'qq-fill',
  'qr-code-fill',
  'qr-scan-2-fill',
  'qr-scan-fill',
  'question-answer-fill',
  'question-fill',
  'questionnaire-fill',
  'quill-pen-fill',
  'radar-fill',
  'radio-2-fill',
  'radio-button-fill',
  'radio-fill',
  'rainy-fill',
  'reactjs-fill',
  'record-circle-fill',
  'record-mail-fill',
  'red-packet-fill',
  'reddit-fill',
  'refresh-fill',
  'refund-fill',
  'remixicon-fill',
  'repeat-2-fill',
  'repeat-fill',
  'repeat-one-fill',
  'reply-fill',
  'reserved-fill',
  'restart-fill',
  'restaurant-2-fill',
  'restaurant-fill',
  'rewind-fill',
  'rewind-mini-fill',
  'rhythm-fill',
  'riding-fill',
  'road-map-fill',
  'roadster-fill',
  'robot-fill',
  'rocket-2-fill',
  'rocket-fill',
  'route-fill',
  'router-fill',
  'rss-fill',
  'ruler-2-fill',
  'ruler-fill',
  'run-fill',
  'safari-fill',
  'safe-2-fill',
  'safe-fill',
  'sailboat-fill',
  'save-2-fill',
  'save-3-fill',
  'save-fill',
  'scan-2-fill',
  'scan-fill',
  'scissors-2-fill',
  'scissors-cut-fill',
  'scissors-fill',
  'screenshot-2-fill',
  'screenshot-fill',
  'sd-card-fill',
  'sd-card-mini-fill',
  'search-2-fill',
  'search-eye-fill',
  'search-fill',
  'send-plane-2-fill',
  'send-plane-fill',
  'sensor-fill',
  'server-fill',
  'settings-2-fill',
  'settings-3-fill',
  'settings-4-fill',
  'settings-5-fill',
  'settings-6-fill',
  'settings-fill',
  'shape-2-fill',
  'shape-fill',
  'share-box-fill',
  'share-circle-fill',
  'share-fill',
  'share-forward-2-fill',
  'share-forward-box-fill',
  'share-forward-fill',
  'shield-cross-fill',
  'shield-fill',
  'shield-flash-fill',
  'shield-star-fill',
  'shield-user-fill',
  'ship-2-fill',
  'ship-fill',
  'shirt-fill',
  'shopping-bag-2-fill',
  'shopping-bag-3-fill',
  'shopping-bag-fill',
  'shopping-cart-2-fill',
  'shopping-cart-fill',
  'showers-fill',
  'shuffle-fill',
  'shut-down-fill',
  'side-bar-fill',
  'signal-tower-fill',
  'sim-card-2-fill',
  'sim-card-fill',
  'sip-fill',
  'skip-back-fill',
  'skip-back-mini-fill',
  'skip-forward-fill',
  'skip-forward-mini-fill',
  'skull-fill',
  'skype-fill',
  'slack-fill',
  'slice-fill',
  'slideshow-2-fill',
  'slideshow-3-fill',
  'slideshow-4-fill',
  'slideshow-fill',
  'smartphone-fill',
  'snapchat-fill',
  'snowy-fill',
  'sound-module-fill',
  'space-ship-fill',
  'spam-2-fill',
  'spam-3-fill',
  'spam-fill',
  'speaker-2-fill',
  'speaker-3-fill',
  'speaker-fill',
  'speed-fill',
  'speed-mini-fill',
  'spotify-fill',
  'stack-fill',
  'stack-overflow-fill',
  'star-fill',
  'star-half-fill',
  'star-half-s-fill',
  'star-s-fill',
  'stock-fill',
  'stop-circle-fill',
  'stop-fill',
  'stop-mini-fill',
  'store-2-fill',
  'store-3-fill',
  'store-fill',
  'subtract-fill',
  'subway-fill',
  'sun-cloudy-fill',
  'sun-fill',
  'sun-foggy-fill',
  'surround-sound-fill',
  'swap-box-fill',
  'swap-fill',
  'switch-fill',
  't-box-fill',
  't-shirt-fill',
  'table-fill',
  'tablet-fill',
  'taobao-fill',
  'tape-fill',
  'task-fill',
  'taxi-fill',
  'telegram-fill',
  'temp-cold-fill',
  'temp-hot-fill',
  'terminal-box-fill',
  'terminal-fill',
  'terminal-window-fill',
  'thumb-down-fill',
  'thumb-up-fill',
  'thunderstorms-fill',
  'time-fill',
  'timer-2-fill',
  'timer-fill',
  'timer-flash-fill',
  'todo-fill',
  'toggle-fill',
  'tornado-fill',
  'traffic-light-fill',
  'train-fill',
  'travesti-fill',
  'treasure-map-fill',
  'trello-fill',
  'trophy-fill',
  'truck-fill',
  'tumblr-fill',
  'tv-2-fill',
  'tv-fill',
  'twitter-fill',
  'u-disk-fill',
  'ubuntu-fill',
  'umbrella-fill',
  'upload-2-fill',
  'upload-cloud-fill',
  'upload-fill',
  'user-2-fill',
  'user-3-fill',
  'user-4-fill',
  'user-5-fill',
  'user-add-fill',
  'user-fill',
  'user-follow-fill',
  'user-location-fill',
  'user-received-2-fill',
  'user-received-fill',
  'user-search-fill',
  'user-settings-fill',
  'user-shared-2-fill',
  'user-shared-fill',
  'user-smile-fill',
  'user-star-fill',
  'user-unfollow-fill',
  'user-voice-fill',
  'video-chat-fill',
  'video-fill',
  'vidicon-2-fill',
  'vidicon-fill',
  'vip-crown-2-fill',
  'vip-crown-fill',
  'vip-diamond-fill',
  'vip-fill',
  'visa-fill',
  'voiceprint-fill',
  'volume-down-fill',
  'volume-mute-fill',
  'volume-up-fill',
  'vuejs-fill',
  'walk-fill',
  'wallet-2-fill',
  'wallet-3-fill',
  'wallet-fill',
  'water-flash-fill',
  'webcam-fill',
  'wechat-2-fill',
  'wechat-fill',
  'wechat-pay-fill',
  'weibo-fill',
  'whatsapp-fill',
  'wifi-fill',
  'window-2-fill',
  'window-fill',
  'windows-fill',
  'windy-fill',
  'women-fill',
  'xbox-fill',
  'youtube-fill',
  'zcool-fill',
  'zhihu-fill',
  'zoom-in-fill',
  'zoom-out-fill'
] as const

export const AVAILABLE_ICON_NAMES = [
  // '4k-line',
  'account-box-line',
  'account-circle-line',
  // 'account-pin-box-line',
  // 'account-pin-circle-line',
  // 'add-box-line',
  // 'add-circle-line',
  // 'add-line',
  // 'admin-line',
  // 'airplay-line',
  // 'alarm-line',
  // 'alarm-warning-line',
  // 'album-line',
  // 'alert-line',
  'alipay-line',
  'amazon-line',
  // 'anchor-line',
  'android-line',
  // 'angularjs-line',
  // 'anticlockwise-2-line',
  // 'anticlockwise-line',
  'apple-line',
  'apps-2-line',
  'apps-line',
  'archive-drawer-line',
  'archive-line',
  // 'arrow-down-circle-line',
  // 'arrow-down-line',
  // 'arrow-down-s-line',
  // 'arrow-drop-down-line',
  // 'arrow-drop-left-line',
  // 'arrow-drop-right-line',
  // 'arrow-drop-up-line',
  // 'arrow-go-back-line',
  // 'arrow-go-forward-line',
  // 'arrow-left-circle-line',
  // 'arrow-left-down-line',
  // 'arrow-left-line',
  // 'arrow-left-s-line',
  // 'arrow-left-up-line',
  // 'arrow-right-circle-line',
  // 'arrow-right-down-line',
  // 'arrow-right-line',
  // 'arrow-right-s-line',
  // 'arrow-right-up-line',
  // 'arrow-up-circle-line',
  // 'arrow-up-line',
  // 'arrow-up-s-line',
  // 'artboard-2-line',
  // 'artboard-line',
  // 'article-line',
  // 'at-line',
  // 'attachment-line',
  // 'award-line',
  'baidu-line',
  // 'ball-pen-line',
  // 'bank-card-2-line',
  // 'bank-card-line',
  // 'bank-line',
  // 'bar-chart-2-line',
  // 'bar-chart-box-line',
  // 'bar-chart-grouped-line',
  // 'bar-chart-horizontal-line',
  // 'bar-chart-line',
  // 'barcode-box-line',
  // 'barcode-line',
  // 'barricade-line',
  // 'base-station-line',
  // 'battery-2-charge-line',
  // 'battery-2-line',
  // 'battery-charge-line',
  // 'battery-line',
  // 'battery-low-line',
  // 'behance-line',
  // 'bike-line',
  'bill-line',
  // 'bit-coin-line',
  // 'bluetooth-connect-line',
  // 'bluetooth-line',
  // 'blur-off-line',
  'book-2-line',
  'book-3-line',
  'book-line',
  // 'book-mark-line',
  // 'book-open-line',
  // 'book-read-line',
  // 'bookmark-2-line',
  // 'bookmark-3-line',
  // 'bookmark-line',
  // 'braces-line',
  // 'brackets-line',
  // 'briefcase-2-line',
  // 'briefcase-3-line',
  // 'briefcase-4-line',
  // 'briefcase-5-line',
  // 'briefcase-line',
  // 'broadcast-line',
  // 'brush-2-line',
  // 'brush-3-line',
  // 'brush-4-line',
  // 'brush-line',
  // 'bug-2-line',
  // 'bug-line',
  // 'building-2-line',
  // 'building-3-line',
  // 'building-4-line',
  // 'building-line',
  // 'bus-2-line',
  'bus-line',
  // 'calculator-line',
  // 'calendar-2-line',
  // 'calendar-event-line',
  // 'calendar-line',
  // 'calendar-todo-line',
  // 'camera-2-line',
  // 'camera-3-line',
  // 'camera-lens-line',
  'camera-line',
  // 'camera-off-line',
  // 'camera-switch-line',
  'car-line',
  // 'car-washing-line',
  'cast-line',
  'cellphone-line',
  // 'celsius-line',
  // 'charging-pile-2-line',
  // 'charging-pile-line',
  'chat-1-line',
  'chat-2-line',
  'chat-3-line',
  'chat-4-line',
  // 'chat-check-line',
  // 'chat-delete-line',
  // 'chat-download-line',
  // 'chat-forward-line',
  // 'chat-heart-line',
  // 'chat-new-line',
  // 'chat-settings-line',
  // 'chat-smile-2-line',
  // 'chat-smile-3-line',
  // 'chat-smile-line',
  // 'chat-upload-line',
  // 'chat-voice-line',
  // 'check-double-line',
  // 'check-line',
  // 'checkbox-blank-circle-line',
  // 'checkbox-blank-line',
  // 'checkbox-circle-line',
  // 'checkbox-indeterminate-line',
  // 'checkbox-line',
  // 'checkbox-multiple-blank-line',
  // 'checkbox-multiple-line',
  // 'china-railway-line',
  'chrome-line',
  // 'clapperboard-line',
  // 'clipboard-line',
  // 'clockwise-2-line',
  // 'clockwise-line',
  // 'close-circle-line',
  // 'close-line',
  // 'cloud-line',
  // 'cloud-windy-line',
  // 'cloudy-2-line',
  // 'cloudy-line',
  // 'code-box-line',
  // 'code-line',
  // 'code-s-line',
  // 'code-s-slash-line',
  // 'codepen-line',
  // 'command-line',
  // 'community-line',
  // 'compass-2-line',
  // 'compass-3-line',
  // 'compass-4-line',
  // 'compass-discover-line',
  // 'compass-line',
  // 'compasses-2-line',
  // 'compasses-line',
  // 'computer-line',
  // 'contacts-book-2-line',
  // 'contacts-book-line',
  // 'contacts-line',
  // 'contrast-2-line',
  // 'contrast-drop-2-line',
  // 'contrast-drop-line',
  // 'contrast-line',
  // 'copper-coin-line',
  // 'copper-diamond-line',
  // 'coreos-line',
  // 'coupon-2-line',
  // 'coupon-3-line',
  // 'coupon-4-line',
  // 'coupon-5-line',
  // 'coupon-line',
  // 'cpu-line',
  // 'crop-2-line',
  // 'crop-line',
  // 'css3-line',
  // 'cup-line',
  // 'currency-line',
  // 'cursor-line',
  // 'customer-service-2-line',
  // 'customer-service-line',
  // 'dashboard-line',
  // 'database-2-line',
  // 'database-line',
  // 'delete-back-2-line',
  // 'delete-back-line',
  // 'delete-bin-2-line',
  // 'delete-bin-3-line',
  // 'delete-bin-4-line',
  // 'delete-bin-5-line',
  // 'delete-bin-6-line',
  // 'delete-bin-7-line',
  // 'delete-bin-line',
  // 'device-line',
  // 'dingding-line',
  // 'direction-line',
  // 'disc-line',
  // 'discord-line',
  // 'discuss-line',
  // 'divide-line',
  // 'door-lock-box-line',
  // 'door-lock-line',
  // 'douban-line',
  // 'download-2-line',
  // 'download-cloud-line',
  // 'download-line',
  // 'drag-move-2-line',
  // 'drag-move-line',
  // 'dribbble-line',
  // 'drive-line',
  // 'drizzle-line',
  // 'drop-line',
  'dropbox-line',
  // 'dv-line',
  // 'dvd-line',
  // 'e-bike-2-line',
  // 'e-bike-line',
  // 'earth-line',
  // 'edge-line',
  // 'edit-2-line',
  // 'edit-box-line',
  // 'edit-circle-line',
  // 'edit-line',
  // 'eject-line',
  // 'emotion-2-line',
  // 'emotion-happy-line',
  // 'emotion-line',
  // 'emotion-normal-line',
  // 'emotion-unhappy-line',
  // 'equalizer-line',
  // 'eraser-line',
  // 'error-warning-line',
  // 'evernote-line',
  // 'exchange-box-line',
  // 'exchange-cny-line',
  // 'exchange-dollar-line',
  // 'exchange-funds-line',
  // 'exchange-line',
  // 'eye-close-line',
  // 'eye-line',
  // 'eye-off-line',
  // 'facebook-box-line',
  // 'facebook-circle-line',
  // 'facebook-line',
  // 'fahrenheit-line',
  // 'feedback-line',
  'file-2-line',
  'file-3-line',
  'file-4-line',
  // 'file-add-line',
  // 'file-chart-2-line',
  // 'file-chart-line',
  // 'file-code-line',
  // 'file-copy-2-line',
  // 'file-copy-line',
  // 'file-damage-line',
  // 'file-download-line',
  // 'file-edit-line',
  // 'file-excel-2-line',
  // 'file-excel-line',
  // 'file-forbid-line',
  // 'file-info-line',
  // 'file-line',
  // 'file-list-2-line',
  // 'file-list-3-line',
  // 'file-list-line',
  // 'file-lock-line',
  // 'file-mark-line',
  // 'file-music-line',
  // 'file-paper-line',
  // 'file-pdf-line',
  // 'file-ppt-2-line',
  // 'file-ppt-line',
  // 'file-reduce-line',
  // 'file-search-line',
  // 'file-settings-line',
  // 'file-shield-2-line',
  // 'file-shield-line',
  // 'file-shred-line',
  // 'file-text-line',
  // 'file-transfer-line',
  // 'file-unknow-line',
  // 'file-upload-line',
  // 'file-user-line',
  // 'file-warning-line',
  // 'file-word-2-line',
  // 'file-word-line',
  // 'file-zip-line',
  // 'film-line',
  // 'filter-2-line',
  // 'filter-3-line',
  // 'filter-line',
  // 'find-replace-line',
  // 'fire-line',
  // 'firefox-line',
  // 'flag-2-line',
  // 'flag-line',
  // 'flash-circle-line',
  // 'flashlight-line',
  // 'flight-land-line',
  // 'flight-takeoff-line',
  // 'focus-2-line',
  // 'focus-line',
  // 'foggy-line',
  'folder-2-line',
  'folder-3-line',
  'folder-4-line',
  'folder-5-line',
  // 'folder-add-line',
  // 'folder-chart-2-line',
  // 'folder-chart-line',
  // 'folder-download-line',
  // 'folder-forbid-line',
  // 'folder-info-line',
  // 'folder-line',
  // 'folder-lock-line',
  // 'folder-music-line',
  // 'folder-received-line',
  // 'folder-reduce-line',
  // 'folder-settings-line',
  // 'folder-shared-line',
  // 'folder-shield-2-line',
  // 'folder-shield-line',
  // 'folder-transfer-line',
  // 'folder-unknow-line',
  // 'folder-upload-line',
  // 'folder-user-line',
  // 'folder-warning-line',
  // 'folders-line',
  // 'footprint-line',
  // 'forbid-2-line',
  // 'forbid-line',
  // 'fullscreen-exit-line',
  // 'fullscreen-line',
  // 'function-line',
  // 'funds-box-line',
  // 'funds-line',
  // 'gallery-line',
  // 'gas-station-line',
  // 'genderless-line',
  // 'git-branch-line',
  // 'git-commit-line',
  // 'git-merge-line',
  // 'git-pull-request-line',
  // 'git-repository-commits-line',
  // 'git-repository-line',
  // 'git-repository-private-line',
  // 'github-line',
  // 'gitlab-line',
  // 'global-line',
  // 'globe-line',
  // 'goblet-line',
  // 'google-line',
  // 'government-line',
  // 'gps-line',
  // 'gradienter-line',
  // 'grid-line',
  // 'group-2-line',
  // 'group-line',
  // 'guide-line',
  // 'hail-line',
  // 'hard-drive-2-line',
  // 'hard-drive-line',
  // 'haze-line',
  // 'hd-line',
  // 'headphone-line',
  // 'heart-2-line',
  // 'heart-line',
  // 'heavy-showers-line',
  // 'home-2-line',
  // 'home-3-line',
  // 'home-4-line',
  // 'home-5-line',
  // 'home-6-line',
  // 'home-7-line',
  // 'home-8-line',
  // 'home-gear-line',
  // 'home-heart-line',
  // 'home-line',
  // 'home-smile-2-line',
  // 'home-smile-line',
  // 'home-wifi-line',
  // 'honour-line',
  // 'hospital-line',
  // 'hotel-bed-line',
  // 'hotel-line',
  // 'hq-line',
  // 'html5-line',
  // 'ie-line',
  // 'image-2-line',
  // 'image-line',
  // 'inbox-archive-line',
  // 'inbox-line',
  // 'increase-decrease-line',
  // 'indeterminate-circle-line',
  // 'information-line',
  // 'input-method-line',
  // 'instagram-line',
  // 'invision-line',
  // 'kakao-talk-line',
  'key-2-line',
  'key-line',
  // 'keyboard-box-line',
  // 'keyboard-line',
  // 'keynote-line',
  // 'landscape-line',
  // 'layout-column-line',
  // 'layout-line',
  // 'layout-row-line',
  // 'lightbulb-flash-line',
  // 'lightbulb-line',
  // 'line-line',
  // 'linkedin-box-line',
  // 'linkedin-line',
  // 'links-line',
  // 'list-settings-line',
  // 'loader-2-line',
  // 'loader-3-line',
  // 'loader-4-line',
  // 'loader-5-line',
  // 'loader-line',
  'lock-2-line',
  'lock-line',
  'lock-password-line',
  'lock-unlock-line'
  // 'login-box-line',
  // 'login-circle-line',
  // 'logout-box-line',
  // 'logout-circle-line',
  // 'mac-line',
  // 'macbook-line',
  // 'magic-line',
  // 'mail-add-line',
  // 'mail-check-line',
  // 'mail-close-line',
  // 'mail-download-line',
  // 'mail-forbid-line',
  // 'mail-line',
  // 'mail-lock-line',
  // 'mail-open-line',
  // 'mail-send-line',
  // 'mail-settings-line',
  // 'mail-star-line',
  // 'mail-unread-line',
  // 'map-2-line',
  // 'map-line',
  // 'map-pin-2-line',
  // 'map-pin-3-line',
  // 'map-pin-4-line',
  // 'map-pin-5-line',
  // 'map-pin-add-line',
  // 'map-pin-line',
  // 'map-pin-range-line',
  // 'map-pin-time-line',
  // 'map-pin-user-line',
  // 'mark-pen-line',
  // 'markdown-line',
  // 'markup-line',
  // 'mastercard-line',
  // 'mastodon-line',
  // 'medium-line',
  // 'men-line',
  // 'menu-2-line',
  // 'menu-3-line',
  // 'menu-line',
  // 'message-2-line',
  // 'message-3-line',
  // 'message-line',
  // 'messenger-line',
  // 'mic-2-line',
  // 'mic-line',
  // 'mic-off-line',
  // 'mini-program-line',
  // 'mist-line',
  // 'money-cny-box-line',
  // 'money-cny-circle-line',
  // 'money-dollar-box-line',
  // 'money-dollar-circle-line',
  // 'money-euro-box-line',
  // 'money-euro-circle-line',
  // 'money-pound-box-line',
  // 'money-pound-circle-line',
  // 'moon-clear-line',
  // 'moon-cloudy-line',
  // 'moon-foggy-line',
  // 'moon-line',
  // 'more-2-line',
  // 'more-line',
  // 'motorbike-line',
  // 'mouse-line',
  // 'movie-2-line',
  // 'movie-line',
  // 'music-2-line',
  // 'music-line',
  // 'mv-line',
  // 'navigation-line',
  // 'netease-cloud-music-line',
  // 'netflix-line',
  // 'newspaper-line',
  // 'notification-2-line',
  // 'notification-3-line',
  // 'notification-4-line',
  // 'notification-badge-line',
  // 'notification-line',
  // 'notification-off-line',
  // 'numbers-line',
  // 'oil-line',
  // 'open-arm-line',
  // 'opera-line',
  // 'order-play-line',
  // 'outlet-2-line',
  // 'outlet-line',
  // 'pages-line',
  // 'paint-brush-line',
  // 'paint-line',
  // 'palette-line',
  // 'pantone-line',
  // 'parent-line',
  // 'parentheses-line',
  // 'parking-box-line',
  // 'parking-line',
  // 'patreon-line',
  // 'pause-circle-line',
  // 'pause-line',
  // 'pause-mini-line',
  // 'paypal-line',
  // 'pen-nib-line',
  // 'pencil-line',
  // 'pencil-ruler-2-line',
  // 'pencil-ruler-line',
  // 'percent-line',
  // 'phone-camera-line',
  // 'phone-line',
  // 'pie-chart-2-line',
  // 'pie-chart-box-line',
  // 'pie-chart-line',
  // 'pin-distance-line',
  // 'pinterest-line',
  // 'plane-line',
  // 'play-circle-line',
  // 'play-line',
  // 'play-list-add-line',
  // 'play-list-line',
  // 'play-mini-line',
  // 'playstation-line',
  // 'plug-2-line',
  // 'plug-line',
  // 'polaroid-2-line',
  // 'polaroid-line',
  // 'police-car-line',
  // 'price-tag-2-line',
  // 'price-tag-3-line',
  // 'price-tag-line',
  // 'printer-line',
  // 'product-hunt-line',
  // 'profile-line',
  // 'projector-2-line',
  // 'projector-line',
  // 'qq-line',
  // 'qr-code-line',
  // 'qr-scan-2-line',
  // 'qr-scan-line',
  // 'question-answer-line',
  // 'question-line',
  // 'questionnaire-line',
  // 'quill-pen-line',
  // 'radar-line',
  // 'radio-2-line',
  // 'radio-button-line',
  // 'radio-line',
  // 'rainy-line',
  // 'reactjs-line',
  // 'record-circle-line',
  // 'record-mail-line',
  // 'red-packet-line',
  // 'reddit-line',
  // 'refresh-line',
  // 'refund-line',
  // 'remixicon-line',
  // 'repeat-2-line',
  // 'repeat-line',
  // 'repeat-one-line',
  // 'reply-line',
  // 'reserved-line',
  // 'restart-line',
  // 'restaurant-2-line',
  // 'restaurant-line',
  // 'rewind-line',
  // 'rewind-mini-line',
  // 'rhythm-line',
  // 'riding-line',
  // 'road-map-line',
  // 'roadster-line',
  // 'robot-line',
  // 'rocket-2-line',
  // 'rocket-line',
  // 'route-line',
  // 'router-line',
  // 'rss-line',
  // 'ruler-2-line',
  // 'ruler-line',
  // 'run-line',
  // 'safari-line',
  // 'safe-2-line',
  // 'safe-line',
  // 'sailboat-line',
  // 'save-2-line',
  // 'save-3-line',
  // 'save-line',
  // 'scan-2-line',
  // 'scan-line',
  // 'scissors-2-line',
  // 'scissors-cut-line',
  // 'scissors-line',
  // 'screenshot-2-line',
  // 'screenshot-line',
  // 'sd-card-line',
  // 'sd-card-mini-line',
  // 'search-2-line',
  // 'search-eye-line',
  // 'search-line',
  // 'send-plane-2-line',
  // 'send-plane-line',
  // 'sensor-line',
  // 'server-line',
  // 'settings-2-line',
  // 'settings-3-line',
  // 'settings-4-line',
  // 'settings-5-line',
  // 'settings-6-line',
  // 'settings-line',
  // 'shape-2-line',
  // 'shape-line',
  // 'share-box-line',
  // 'share-circle-line',
  // 'share-forward-2-line',
  // 'share-forward-box-line',
  // 'share-forward-line',
  // 'share-line',
  // 'shield-cross-line',
  // 'shield-flash-line',
  // 'shield-line',
  // 'shield-star-line',
  // 'shield-user-line',
  // 'ship-2-line',
  // 'ship-line',
  // 'shirt-line',
  // 'shopping-bag-2-line',
  // 'shopping-bag-3-line',
  // 'shopping-bag-line',
  // 'shopping-cart-2-line',
  // 'shopping-cart-line',
  // 'showers-line',
  // 'shuffle-line',
  // 'shut-down-line',
  // 'side-bar-line',
  // 'signal-tower-line',
  // 'sim-card-2-line',
  // 'sim-card-line',
  // 'sip-line',
  // 'skip-back-line',
  // 'skip-back-mini-line',
  // 'skip-forward-line',
  // 'skip-forward-mini-line',
  // 'skull-line',
  // 'skype-line',
  // 'slack-line',
  // 'slice-line',
  // 'slideshow-2-line',
  // 'slideshow-3-line',
  // 'slideshow-4-line',
  // 'slideshow-line',
  // 'smartphone-line',
  // 'snapchat-line',
  // 'snowy-line',
  // 'sound-module-line',
  // 'space-ship-line',
  // 'spam-2-line',
  // 'spam-3-line',
  // 'spam-line',
  // 'speaker-2-line',
  // 'speaker-3-line',
  // 'speaker-line',
  // 'speed-line',
  // 'speed-mini-line',
  // 'spotify-line',
  // 'stack-line',
  // 'stack-overflow-line',
  // 'star-half-line',
  // 'star-half-s-line',
  // 'star-line',
  // 'star-s-line',
  // 'stock-line',
  // 'stop-circle-line',
  // 'stop-line',
  // 'stop-mini-line',
  // 'store-2-line',
  // 'store-3-line',
  // 'store-line',
  // 'subtract-line',
  // 'subway-line',
  // 'sun-cloudy-line',
  // 'sun-foggy-line',
  // 'sun-line',
  // 'surround-sound-line',
  // 'swap-box-line',
  // 'swap-line',
  // 'switch-line',
  // 't-box-line',
  // 't-shirt-line',
  // 'table-line',
  // 'tablet-line',
  // 'taobao-line',
  // 'tape-line',
  // 'task-line',
  // 'taxi-line',
  // 'telegram-line',
  // 'temp-cold-line',
  // 'temp-hot-line',
  // 'terminal-box-line',
  // 'terminal-line',
  // 'terminal-window-line',
  // 'thumb-down-line',
  // 'thumb-up-line',
  // 'thunderstorms-line',
  // 'time-line',
  // 'timer-2-line',
  // 'timer-flash-line',
  // 'timer-line',
  // 'todo-line',
  // 'toggle-line',
  // 'tornado-line',
  // 'traffic-light-line',
  // 'train-line',
  // 'travesti-line',
  // 'treasure-map-line',
  // 'trello-line',
  // 'trophy-line',
  // 'truck-line',
  // 'tumblr-line',
  // 'tv-2-line',
  // 'tv-line',
  // 'twitter-line',
  // 'u-disk-line',
  // 'ubuntu-line',
  // 'umbrella-line',
  // 'upload-2-line',
  // 'upload-cloud-line',
  // 'upload-line',
  // 'user-2-line',
  // 'user-3-line',
  // 'user-4-line',
  // 'user-5-line',
  // 'user-add-line',
  // 'user-follow-line',
  // 'user-line',
  // 'user-location-line',
  // 'user-received-2-line',
  // 'user-received-line',
  // 'user-search-line',
  // 'user-settings-line',
  // 'user-shared-2-line',
  // 'user-shared-line',
  // 'user-smile-line',
  // 'user-star-line',
  // 'user-unfollow-line',
  // 'user-voice-line',
  // 'video-chat-line',
  // 'video-line',
  // 'vidicon-2-line',
  // 'vidicon-line',
  // 'vip-crown-2-line',
  // 'vip-crown-line',
  // 'vip-diamond-line',
  // 'vip-line',
  // 'visa-line',
  // 'voiceprint-line',
  // 'volume-down-line',
  // 'volume-mute-line',
  // 'volume-up-line',
  // 'vuejs-line',
  // 'walk-line',
  // 'wallet-2-line',
  // 'wallet-3-line',
  // 'wallet-line',
  // 'water-flash-line',
  // 'webcam-line',
  // 'wechat-2-line',
  // 'wechat-line',
  // 'wechat-pay-line',
  // 'weibo-line',
  // 'whatsapp-line',
  // 'wifi-line',
  // 'window-2-line',
  // 'window-line',
  // 'windows-line',
  // 'windy-line',
  // 'women-line',
  // 'xbox-line',
  // 'youtube-line',
  // 'zcool-line',
  // 'zhihu-line',
  // 'zoom-in-line',
  // 'zoom-out-line'
] as const

export type IconName =  // typeof AVAILABLE_ICON_NAMES[number]
  | typeof NORMAL_ICON_NAMES[number]
  | typeof OUTLINED_ICON_NAMES[number]
  | typeof FILLED_ICON_NAMES[number]
