export const CHANGE_GROUPS = 'CHANGE_GROUPS'
export const CHANGE_GROUP = 'SELECT_GROUP'
export const MODIFY_GROUP = 'MODIFY_GROUP'

export const CHANGE_ENTRIES = 'CHANGE_ENTRIES'
export const CHANGE_ENTRY = 'CHANGE_ENTRY'
export const MODIFY_ENTRY = 'MODIFY_ENTRY'

export const CHANGE_FIELDS = 'CHANGE_FIELDS'
export const MODIFY_FIELD = 'MODIFY_FIELD'
