export const CHANGE_GROUPS = 'SET_GROUPS'
export const CHANGE_GROUP = 'SELECT_GROUP'
export const MODIFY_GROUP = 'MODIFY_GROUP'

export const CHANGE_ENTRIES = 'SET_ENTRIES'
export const CHANGE_ENTRY = 'SET_ENTRY'
export const MODIFY_ENTRY = 'MODIFY_ENTRY'

export const CHANGE_FIELDS = 'SET_FIELDS'
